name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Create symlink from public/assets/ to src/assets/
      - name: Create assets symlink
        run: |
          mkdir -p public/assets
          ln -s $(pwd)/src/assets/contact.vcf public/assets/contact.vcf
          
      # Deploy public/ folder to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
